test: Add wait_for() shell helper
Add a shell helper function to wait for some command to succeed - typically
a test for something to be done by a background process.  Use it in the
context code which waits for the guest to respond to ssh-over-vsock
connections.

Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
Signed-off-by: Stefano Brivio <sbrivio@redhat.com>

diff --git a/test/lib/util b/test/lib/util
--- a/test/lib/util
+++ b/test/lib/util
@@ -123,3 +123,11 @@ get_info_cols() {
 		__j=$((__j + 1))
 	done
 }
+
+# wait_for() - Retry a command until it succeeds
+# $@:	Command to run
+wait_for() {
+        while ! "$@"; do
+                sleep 0.1 || sleep 1
+        done
+}
